version: 1
rules:
  # Rule 1: If I change the Auth system, I must update the Auth Docs
  - id: "auth-check"
    files: "src/main/java/com/myapp/auth/**/*.java"   # Watch these files
    docs: "docs/authentication.md"                    # Require this doc

  # Rule 2: If I change any API Controller, I must update the API Spec
  - id: "api-check"
    files: "src/main/java/com/myapp/api/**/*.java"
    docs: "docs/api-reference.md"